application: myapp
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.*\.html)$
  static_files: \1
  upload: .*\.html$

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: _go_app
